import { defineConfig } from 'test-proxy-recorder'

// Generated by `test-proxy-recorder init`.
// Auto-discovered when you run `test-proxy-recorder` with no arguments.
// CLI flags always override the values set here.
export default defineConfig({
  // Backend the proxy records against. Point your app's API base URL here too.
  target: 'https://x.com',

  // Port the proxy listens on. Matches the Playwright client default
  // (override both with the TEST_PROXY_RECORDER_PORT env var).
  port: 8100,

  // Where .mock.json recordings are written, relative to this file.
  // Commit this directory — CI replays from it.
  recordingsDir: './e2e/recordings',

  // Strip credentials from recordings before they touch disk. The defaults
  // (Authorization / Cookie / Set-Cookie) cover X's bearer token and the
  // auth_token session cookie; x-csrf-token is X's CSRF header (ct0).
  redaction: {
    headers: ['x-csrf-token'],
  },
})
