export const COUNTRY_FLAGS: Record<string, string> = {
  Afghanistan: '🇦🇫',
  Albania: '🇦🇱',
  Algeria: '🇩🇿',
  Andorra: '🇦🇩',
  Angola: '🇦🇴',
  'Antigua and Barbuda': '🇦🇬',
  Argentina: '🇦🇷',
  Armenia: '🇦🇲',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Azerbaijan: '🇦🇿',
  Bahamas: '🇧🇸',
  Bahrain: '🇧🇭',
  Bangladesh: '🇧🇩',
  Barbados: '🇧🇧',
  Belarus: '🇧🇾',
  Belgium: '🇧🇪',
  Belize: '🇧🇿',
  Benin: '🇧🇯',
  Bhutan: '🇧🇹',
  Bolivia: '🇧🇴',
  'Bosnia and Herzegovina': '🇧🇦',
  Botswana: '🇧🇼',
  Brazil: '🇧🇷',
  Brunei: '🇧🇳',
  Bulgaria: '🇧🇬',
  'Burkina Faso': '🇧🇫',
  Burundi: '🇧🇮',
  'Cabo Verde': '🇨🇻',
  Cambodia: '🇰🇭',
  Cameroon: '🇨🇲',
  Canada: '🇨🇦',
  'Central African Republic': '🇨🇫',
  Chad: '🇹🇩',
  Chile: '🇨🇱',
  China: '🇨🇳',
  Colombia: '🇨🇴',
  Comoros: '🇰🇲',
  Congo: '🇨🇬',
  'Costa Rica': '🇨🇷',
  Croatia: '🇭🇷',
  Cuba: '🇨🇺',
  Cyprus: '🇨🇾',
  'Czech Republic': '🇨🇿',
  Czechia: '🇨🇿',
  'Democratic Republic of the Congo': '🇨🇩',
  Denmark: '🇩🇰',
  Djibouti: '🇩🇯',
  Dominica: '🇩🇲',
  'Dominican Republic': '🇩🇴',
  Ecuador: '🇪🇨',
  Egypt: '🇪🇬',
  'El Salvador': '🇸🇻',
  'Equatorial Guinea': '🇬🇶',
  Eritrea: '🇪🇷',
  Estonia: '🇪🇪',
  Eswatini: '🇸🇿',
  Ethiopia: '🇪🇹',
  Fiji: '🇫🇯',
  Finland: '🇫🇮',
  France: '🇫🇷',
  Gabon: '🇬🇦',
  Gambia: '🇬🇲',
  Georgia: '🇬🇪',
  Germany: '🇩🇪',
  Ghana: '🇬🇭',
  Greece: '🇬🇷',
  Grenada: '🇬🇩',
  Guatemala: '🇬🇹',
  Guinea: '🇬🇳',
  'Guinea-Bissau': '🇬🇼',
  Guyana: '🇬🇾',
  Haiti: '🇭🇹',
  Honduras: '🇭🇳',
  'Hong Kong': '🇭🇰',
  Hungary: '🇭🇺',
  Iceland: '🇮🇸',
  India: '🇮🇳',
  Indonesia: '🇮🇩',
  Iran: '🇮🇷',
  Iraq: '🇮🇶',
  Ireland: '🇮🇪',
  'Isle of Man': '🇮🇲',
  Israel: '🇮🇱',
  Italy: '🇮🇹',
  Jamaica: '🇯🇲',
  Japan: '🇯🇵',
  Jordan: '🇯🇴',
  Kazakhstan: '🇰🇿',
  Kenya: '🇰🇪',
  Kiribati: '🇰🇮',
  Kosovo: '🇽🇰',
  Kuwait: '🇰🇼',
  Kyrgyzstan: '🇰🇬',
  Laos: '🇱🇦',
  Latvia: '🇱🇻',
  Lebanon: '🇱🇧',
  Lesotho: '🇱🇸',
  Liberia: '🇱🇷',
  Libya: '🇱🇾',
  Liechtenstein: '🇱🇮',
  Lithuania: '🇱🇹',
  Luxembourg: '🇱🇺',
  Macedonia: '🇲🇰',
  Madagascar: '🇲🇬',
  Malawi: '🇲🇼',
  Malaysia: '🇲🇾',
  Maldives: '🇲🇻',
  Mali: '🇲🇱',
  Malta: '🇲🇹',
  'Marshall Islands': '🇲🇭',
  Mauritania: '🇲🇷',
  Mauritius: '🇲🇺',
  Mexico: '🇲🇽',
  Micronesia: '🇫🇲',
  Moldova: '🇲🇩',
  Monaco: '🇲🇨',
  Mongolia: '🇲🇳',
  Montenegro: '🇲🇪',
  Morocco: '🇲🇦',
  Mozambique: '🇲🇿',
  Myanmar: '🇲🇲',
  Namibia: '🇳🇦',
  Nauru: '🇳🇷',
  Nepal: '🇳🇵',
  Netherlands: '🇳🇱',
  'New Zealand': '🇳🇿',
  Nicaragua: '🇳🇮',
  Niger: '🇳🇪',
  Nigeria: '🇳🇬',
  'North Korea': '🇰🇵',
  'North Macedonia': '🇲🇰',
  Norway: '🇳🇴',
  Oman: '🇴🇲',
  Pakistan: '🇵🇰',
  Palau: '🇵🇼',
  Panama: '🇵🇦',
  'Papua New Guinea': '🇵🇬',
  Paraguay: '🇵🇾',
  Peru: '🇵🇪',
  Philippines: '🇵🇭',
  Poland: '🇵🇱',
  Portugal: '🇵🇹',
  'Puerto Rico': '🇵🇷',
  Qatar: '🇶🇦',
  Romania: '🇷🇴',
  'Russian Federation': '🇷🇺',
  Rwanda: '🇷🇼',
  'Saint Kitts and Nevis': '🇰🇳',
  'Saint Lucia': '🇱🇨',
  'Saint Vincent and the Grenadines': '🇻🇨',
  Samoa: '🇼🇸',
  'San Marino': '🇸🇲',
  'Sao Tome and Principe': '🇸🇹',
  'Saudi Arabia': '🇸🇦',
  Senegal: '🇸🇳',
  Serbia: '🇷🇸',
  Seychelles: '🇸🇨',
  'Sierra Leone': '🇸🇱',
  Singapore: '🇸🇬',
  Slovakia: '🇸🇰',
  Slovenia: '🇸🇮',
  'Solomon Islands': '🇸🇧',
  Somalia: '🇸🇴',
  'South Africa': '🇿🇦',
  Korea: '🇰🇷',
  'South Sudan': '🇸🇸',
  Spain: '🇪🇸',
  'Sri Lanka': '🇱🇰',
  Sudan: '🇸🇩',
  Suriname: '🇸🇷',
  Sweden: '🇸🇪',
  Switzerland: '🇨🇭',
  Syria: '🇸🇾',
  Taiwan: '🇹🇼',
  Tajikistan: '🇹🇯',
  Tanzania: '🇹🇿',
  Thailand: '🇹🇭',
  'Timor-Leste': '🇹🇱',
  Togo: '🇹🇬',
  Tonga: '🇹🇴',
  'Trinidad and Tobago': '🇹🇹',
  Tunisia: '🇹🇳',
  Turkey: '🇹🇷',
  Turkmenistan: '🇹🇲',
  Tuvalu: '🇹🇻',
  Uganda: '🇺🇬',
  Ukraine: '🇺🇦',
  'United Arab Emirates': '🇦🇪',
  'United Kingdom': '🇬🇧',
  'United States': '🇺🇸',
  Uruguay: '🇺🇾',
  Uzbekistan: '🇺🇿',
  Vanuatu: '🇻🇺',
  'Vatican City': '🇻🇦',
  Venezuela: '🇻🇪',
  'Viet Nam': '🇻🇳',
  Yemen: '🇾🇪',
  Zambia: '🇿🇲',
  Zimbabwe: '🇿🇼',
}

export const REGION_FLAGS: Record<string, string> = {
  Africa: '🌏',
  Australasia: '🌏',
  'East Asia & Pacific': '🌏',
  'Eastern Europe': '🌏',
  'Eastern Europe (Non-EU)': '🌏',
  Europe: '🇪🇺',
  'North Africa': '🌍',
  'North America': '🌎',
  'South America': '🌎',
  'East Asia': '🌏',
  'Central Asia': '🌎',
  'South Asia': '🌏',
  'Southeast Asia': '🌏',
  'West Asia': '🌍',
}

export const REGION_ABBR: Record<string, string> = {
  Africa: 'AFR',
  Australasia: 'AUS',
  'East Asia & Pacific': 'EAP',
  'Eastern Europe': 'EEUR',
  'Eastern Europe (Non-EU)': 'EEUR',
  Europe: 'EUR',
  'North Africa': 'NAF',
  'North America': 'NAM',
  'East Asia': 'EAS',
  'South America': 'SAM',
  'Central Asia': 'CAS',
  'South Asia': 'SAS',
  'Southeast Asia': 'SEAS',
  'West Asia': 'WAS',
}

export const BLOCKED_COUNTRIES_KEY = 'blockedCountries'
export const HIGHLIGHT_KEYWORDS_KEY = 'highlightKeywords'
export const HIGHLIGHT_FLAGS_KEY = 'highlightFlags'
export const SHOW_LOCATION_IN_FEED_KEY = 'showLocationInFeed'
// Usernames (lowercased) that should never be highlighted, even when they match
// a keyword or flag rule — e.g. accounts using a keyword sarcastically ("no NAFO").
export const HIGHLIGHT_EXCEPTIONS_KEY = 'highlightExceptions'
// Whether to show the "Don't highlight" toggle button on profile hover cards.
export const SHOW_EXCEPTION_BUTTON_KEY = 'showExceptionButton'
// How to treat tweets whose author's location is on the blocked list (reuses
// BLOCKED_COUNTRIES_KEY). Stores a HideBlockedMode; 'collapse' by default.
//   'off'      — show normally
//   'collapse' — replace with a slim placeholder that can be expanded ("Show")
//   'hide'     — remove silently (display:none), no trace
export const HIDE_BLOCKED_LOCATIONS_KEY = 'hideBlockedLocations'

export type HideBlockedMode = 'off' | 'collapse' | 'hide'

// Defaults to 'collapse' when nothing is stored. An explicitly-chosen 'off' is
// preserved (recognized here), so the user can still fully disable hiding.
export function normalizeHideBlockedMode(value: unknown): HideBlockedMode {
  return value === 'off' || value === 'collapse' || value === 'hide'
    ? value
    : 'collapse'
}
// Whether to use the shared community location cache (query it on load and
// contribute AboutAccountQuery results back). Opt-in; inert unless the server
// URL (CACHE_API_BASE in constants.ts) is configured.
export const SHARED_CACHE_KEY = 'sharedCacheEnabled'

// Whether to prefetch locations in the background for on-screen accounts
// (most-followed first), warming the local + community caches so flags appear
// without hovering. Uses at most half the rate-limit window; defaults on.
export const BACKGROUND_PREFETCH_KEY = 'backgroundPrefetch'

export const DEFAULT_BLOCKED_COUNTRIES = [
  'Africa',
  'India',
  'South Asia',
  'Nigeria',
  'Pakistan',
  'Bangladesh',
]
