/**
 * Generated by `pnpm tests:count` — do not edit by hand.
 *
 * What `vitest list` collects, so the number the site publishes is the number
 * `pnpm test` runs.
 */
export const TEST_COUNT = 1007
export const SERVER_TEST_COUNT = 90
