export const COUNTRY_FLAGS: Record<string, string> = {
  Afghanistan: '🇦🇫',
  Albania: '🇦🇱',
  Algeria: '🇩🇿',
  Andorra: '🇦🇩',
  Angola: '🇦🇴',
  'Antigua and Barbuda': '🇦🇬',
  Argentina: '🇦🇷',
  Armenia: '🇦🇲',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Azerbaijan: '🇦🇿',
  Bahamas: '🇧🇸',
  Bahrain: '🇧🇭',
  Bangladesh: '🇧🇩',
  Barbados: '🇧🇧',
  Belarus: '🇧🇾',
  Belgium: '🇧🇪',
  Belize: '🇧🇿',
  Benin: '🇧🇯',
  Bhutan: '🇧🇹',
  Bolivia: '🇧🇴',
  'Bosnia and Herzegovina': '🇧🇦',
  Botswana: '🇧🇼',
  Brazil: '🇧🇷',
  Brunei: '🇧🇳',
  Bulgaria: '🇧🇬',
  'Burkina Faso': '🇧🇫',
  Burundi: '🇧🇮',
  'Cabo Verde': '🇨🇻',
  Cambodia: '🇰🇭',
  Cameroon: '🇨🇲',
  Canada: '🇨🇦',
  'Central African Republic': '🇨🇫',
  Chad: '🇹🇩',
  Chile: '🇨🇱',
  China: '🇨🇳',
  Colombia: '🇨🇴',
  Comoros: '🇰🇲',
  Congo: '🇨🇬',
  'Costa Rica': '🇨🇷',
  Croatia: '🇭🇷',
  Cuba: '🇨🇺',
  Cyprus: '🇨🇾',
  'Czech Republic': '🇨🇿',
  Czechia: '🇨🇿',
  'Democratic Republic of the Congo': '🇨🇩',
  Denmark: '🇩🇰',
  Djibouti: '🇩🇯',
  Dominica: '🇩🇲',
  'Dominican Republic': '🇩🇴',
  Ecuador: '🇪🇨',
  Egypt: '🇪🇬',
  'El Salvador': '🇸🇻',
  'Equatorial Guinea': '🇬🇶',
  Eritrea: '🇪🇷',
  Estonia: '🇪🇪',
  Eswatini: '🇸🇿',
  Ethiopia: '🇪🇹',
  Fiji: '🇫🇯',
  Finland: '🇫🇮',
  France: '🇫🇷',
  Gabon: '🇬🇦',
  Gambia: '🇬🇲',
  Georgia: '🇬🇪',
  Germany: '🇩🇪',
  Ghana: '🇬🇭',
  Greece: '🇬🇷',
  Grenada: '🇬🇩',
  Guatemala: '🇬🇹',
  Guinea: '🇬🇳',
  'Guinea-Bissau': '🇬🇼',
  Guyana: '🇬🇾',
  Haiti: '🇭🇹',
  Honduras: '🇭🇳',
  'Hong Kong': '🇭🇰',
  Hungary: '🇭🇺',
  Iceland: '🇮🇸',
  India: '🇮🇳',
  Indonesia: '🇮🇩',
  Iran: '🇮🇷',
  Iraq: '🇮🇶',
  Ireland: '🇮🇪',
  'Isle of Man': '🇮🇲',
  Israel: '🇮🇱',
  Italy: '🇮🇹',
  'Ivory Coast': '🇨🇮',
  Jamaica: '🇯🇲',
  Japan: '🇯🇵',
  Jordan: '🇯🇴',
  Kazakhstan: '🇰🇿',
  Kenya: '🇰🇪',
  Kiribati: '🇰🇮',
  Kosovo: '🇽🇰',
  Kuwait: '🇰🇼',
  Kyrgyzstan: '🇰🇬',
  Laos: '🇱🇦',
  Latvia: '🇱🇻',
  Lebanon: '🇱🇧',
  Lesotho: '🇱🇸',
  Liberia: '🇱🇷',
  Libya: '🇱🇾',
  Liechtenstein: '🇱🇮',
  Lithuania: '🇱🇹',
  Luxembourg: '🇱🇺',
  Macedonia: '🇲🇰',
  Madagascar: '🇲🇬',
  Malawi: '🇲🇼',
  Malaysia: '🇲🇾',
  Maldives: '🇲🇻',
  Mali: '🇲🇱',
  Malta: '🇲🇹',
  'Marshall Islands': '🇲🇭',
  Mauritania: '🇲🇷',
  Mauritius: '🇲🇺',
  Mexico: '🇲🇽',
  Micronesia: '🇫🇲',
  Moldova: '🇲🇩',
  Monaco: '🇲🇨',
  Mongolia: '🇲🇳',
  Montenegro: '🇲🇪',
  Morocco: '🇲🇦',
  Mozambique: '🇲🇿',
  Myanmar: '🇲🇲',
  Namibia: '🇳🇦',
  Nauru: '🇳🇷',
  Nepal: '🇳🇵',
  Netherlands: '🇳🇱',
  'New Zealand': '🇳🇿',
  Nicaragua: '🇳🇮',
  Niger: '🇳🇪',
  Nigeria: '🇳🇬',
  'North Korea': '🇰🇵',
  'North Macedonia': '🇲🇰',
  Norway: '🇳🇴',
  Oman: '🇴🇲',
  Pakistan: '🇵🇰',
  Palau: '🇵🇼',
  Palestine: '🇵🇸',
  Panama: '🇵🇦',
  'Papua New Guinea': '🇵🇬',
  Paraguay: '🇵🇾',
  Peru: '🇵🇪',
  Philippines: '🇵🇭',
  Poland: '🇵🇱',
  Portugal: '🇵🇹',
  'Puerto Rico': '🇵🇷',
  Qatar: '🇶🇦',
  Romania: '🇷🇴',
  'Russian Federation': '🇷🇺',
  Rwanda: '🇷🇼',
  'Saint Kitts and Nevis': '🇰🇳',
  'Saint Lucia': '🇱🇨',
  'Saint Vincent and the Grenadines': '🇻🇨',
  Samoa: '🇼🇸',
  'San Marino': '🇸🇲',
  'Sao Tome and Principe': '🇸🇹',
  'Saudi Arabia': '🇸🇦',
  Senegal: '🇸🇳',
  Serbia: '🇷🇸',
  Seychelles: '🇸🇨',
  'Sierra Leone': '🇸🇱',
  Singapore: '🇸🇬',
  Slovakia: '🇸🇰',
  Slovenia: '🇸🇮',
  'Solomon Islands': '🇸🇧',
  Somalia: '🇸🇴',
  'South Africa': '🇿🇦',
  Korea: '🇰🇷',
  'South Sudan': '🇸🇸',
  Spain: '🇪🇸',
  'Sri Lanka': '🇱🇰',
  Sudan: '🇸🇩',
  Suriname: '🇸🇷',
  Sweden: '🇸🇪',
  Switzerland: '🇨🇭',
  Syria: '🇸🇾',
  Taiwan: '🇹🇼',
  Tajikistan: '🇹🇯',
  Tanzania: '🇹🇿',
  Thailand: '🇹🇭',
  'Timor-Leste': '🇹🇱',
  Togo: '🇹🇬',
  Tonga: '🇹🇴',
  'Trinidad and Tobago': '🇹🇹',
  Tunisia: '🇹🇳',
  Turkey: '🇹🇷',
  Turkmenistan: '🇹🇲',
  Tuvalu: '🇹🇻',
  Uganda: '🇺🇬',
  Ukraine: '🇺🇦',
  'United Arab Emirates': '🇦🇪',
  'United Kingdom': '🇬🇧',
  'United States': '🇺🇸',
  Uruguay: '🇺🇾',
  Uzbekistan: '🇺🇿',
  Vanuatu: '🇻🇺',
  'Vatican City': '🇻🇦',
  Venezuela: '🇻🇪',
  'Viet Nam': '🇻🇳',
  Yemen: '🇾🇪',
  Zambia: '🇿🇲',
  Zimbabwe: '🇿🇼',

  // X reports these in their own right ("Jersey App Store"), so the question is
  // whether X can name it, not who governs it.
  Anguilla: '🇦🇮',
  Aruba: '🇦🇼',
  Bermuda: '🇧🇲',
  'British Virgin Islands': '🇻🇬',
  'Cayman Islands': '🇰🇾',
  'Christmas Island': '🇨🇽',
  'Cook Islands': '🇨🇰',
  Curaçao: '🇨🇼',
  'Falkland Islands': '🇫🇰',
  'Faroe Islands': '🇫🇴',
  'French Guiana': '🇬🇫',
  'French Polynesia': '🇵🇫',
  Gibraltar: '🇬🇮',
  Greenland: '🇬🇱',
  Guadeloupe: '🇬🇵',
  Guam: '🇬🇺',
  Guernsey: '🇬🇬',
  Jersey: '🇯🇪',
  Macau: '🇲🇴',
  Martinique: '🇲🇶',
  Mayotte: '🇾🇹',
  Montserrat: '🇲🇸',
  'New Caledonia': '🇳🇨',
  'Northern Mariana Islands': '🇲🇵',
  Réunion: '🇷🇪',
  'Saint Barthélemy': '🇧🇱',
  'Saint Martin': '🇲🇫',
  'Saint Pierre and Miquelon': '🇵🇲',
  'Sint Maarten': '🇸🇽',
  'Turks and Caicos Islands': '🇹🇨',
  'U.S. Virgin Islands': '🇻🇮',
  'Wallis and Futuna': '🇼🇫',
  'Western Sahara': '🇪🇭',
  'American Samoa': '🇦🇸',
  'Åland Islands': '🇦🇽',
}

export const REGION_FLAGS: Record<string, string> = {
  Africa: '🌏',
  Australasia: '🌏',
  'East Asia & Pacific': '🌏',
  'Eastern Europe': '🌏',
  'Eastern Europe (Non-EU)': '🌏',
  Europe: '🇪🇺',
  'North Africa': '🌍',
  'North America': '🌎',
  'South America': '🌎',
  'East Asia': '🌏',
  'Central Asia': '🌏',
  'South Asia': '🌏',
  'Southeast Asia': '🌏',
  'West Asia': '🌍',
}

export const REGION_ABBR: Record<string, string> = {
  Africa: 'AFR',
  Australasia: 'AUS',
  'East Asia & Pacific': 'EAP',
  'Eastern Europe': 'EEUR',
  'Eastern Europe (Non-EU)': 'EEUR',
  Europe: 'EUR',
  'North Africa': 'NAF',
  'North America': 'NAM',
  'East Asia': 'EAS',
  'South America': 'SAM',
  'Central Asia': 'CAS',
  'South Asia': 'SAS',
  'Southeast Asia': 'SEAS',
  'West Asia': 'WAS',
}

/** The marker for a canonical name — a country flag, a region flag, or 🌐. */
export function flagFor(canonical: string): string {
  return COUNTRY_FLAGS[canonical] ?? REGION_FLAGS[canonical] ?? '🌐'
}

/** flagFor for a location X reported, whatever spelling it used for it. */
export function flagEmojiFor(location: string): string {
  return flagFor(canonicalLocation(location))
}

// Keyed by the canonical name, which is the vocabulary X itself reports. An
// alias that is also a flag key stops being offered separately in the picker.
export const LOCATION_ALIASES: Record<string, string[]> = {
  Afghanistan: ['AF'],
  Algeria: ['DZ'],
  'Antigua and Barbuda': ['Antigua', 'Barbuda'],
  Argentina: ['AR'],
  Australia: ['AU', 'AUS', 'Oz'],
  Austria: ['Österreich', 'Osterreich', 'AT'],
  Bahamas: ['The Bahamas'],
  Bangladesh: ['BD'],
  Belarus: ['BY', 'Byelorussia', 'White Russia'],
  Belgium: ['België', 'Belgie', 'Belgique', 'BE'],
  Belize: ['British Honduras'],
  Benin: ['Dahomey'],
  Bolivia: ['Plurinational State of Bolivia'],
  'Bosnia and Herzegovina': ['Bosnia', 'Herzegovina', 'BiH'],
  Brazil: ['Brasil', 'BR'],
  Brunei: ['Brunei Darussalam'],
  Bulgaria: ['BG'],
  'Burkina Faso': ['Upper Volta'],
  'Cabo Verde': ['Cape Verde'],
  Cambodia: ['Kampuchea', 'KH'],
  Canada: ['CA', 'CAN'],
  'Central African Republic': ['CAR'],
  China: ['PRC', "People's Republic of China", 'Mainland China', 'CN'],
  Colombia: ['CO'],
  Congo: ['Republic of the Congo', 'Congo-Brazzaville'],
  'Costa Rica': ['CR'],
  Croatia: ['Hrvatska', 'HR'],
  Cuba: ['CU'],
  Cyprus: ['CY'],
  Czechia: ['Czech Republic', 'Czech', 'CZ'],
  'Democratic Republic of the Congo': [
    'DRC',
    'DR Congo',
    'Congo-Kinshasa',
    'Zaire',
  ],
  Denmark: ['Danmark', 'DK'],
  'Dominican Republic': ['DR'],
  Ecuador: ['EC'],
  Egypt: ['Arab Republic of Egypt', 'Misr'],
  'El Salvador': ['SV'],
  Estonia: ['Eesti', 'EE'],
  Eswatini: ['Swaziland'],
  Ethiopia: ['ET'],
  Finland: ['Suomi', 'FI'],
  France: ['FR'],
  Germany: ['Deutschland', 'DE', 'GER'],
  Greece: ['Hellas', 'Ellada', 'GR'],
  Guatemala: ['GT'],
  'Guinea-Bissau': ['Guinea Bissau'],
  Haiti: ['HT'],
  Honduras: ['HN'],
  'Hong Kong': ['HK', 'Hong Kong SAR'],
  Hungary: ['Magyarország', 'Magyarorszag', 'HU'],
  Iceland: ['Ísland', 'Island'],
  India: ['Bharat', 'Hindustan', 'IN'],
  Indonesia: ['ID'],
  Iran: ['Persia', 'Islamic Republic of Iran'],
  Iraq: ['IQ'],
  Ireland: ['Republic of Ireland', 'Éire', 'Eire', 'IE'],
  'Isle of Man': ['IOM'],
  Israel: ['IL'],
  Italy: ['Italia', 'IT'],
  'Ivory Coast': ["Côte d'Ivoire", "Cote d'Ivoire", 'Cote dIvoire'],
  Japan: ['Nippon', 'Nihon', 'JP'],
  Jordan: ['JO'],
  Kazakhstan: ['KZ'],
  Kenya: ['KE'],
  Korea: ['South Korea', 'Republic of Korea', 'ROK', 'KR'],
  Kyrgyzstan: ['Kyrgyz Republic', 'Kirghizia'],
  Laos: ["Lao People's Democratic Republic", 'Lao PDR'],
  Latvia: ['LV'],
  Lebanon: ['LB'],
  Lithuania: ['Lietuva', 'LT'],
  Luxembourg: ['LU'],
  Malaysia: ['MY'],
  Maldives: ['MV'],
  Malta: ['MT'],
  Mexico: ['México', 'MX'],
  Micronesia: ['Federated States of Micronesia', 'FSM'],
  Moldova: ['Republic of Moldova'],
  Mongolia: ['MN'],
  Montenegro: ['Crna Gora'],
  Morocco: ['Maroc', 'MA'],
  Myanmar: ['Burma'],
  Nepal: ['NP'],
  Netherlands: ['Holland', 'The Netherlands', 'Nederland', 'NL'],
  'New Zealand': ['NZ', 'Aotearoa'],
  Nicaragua: ['NI'],
  Nigeria: ['NG'],
  'North Korea': ['DPRK', "Democratic People's Republic of Korea"],
  'North Macedonia': ['Macedonia', 'FYROM'],
  Norway: ['Norge', 'NO'],
  Pakistan: ['PK'],
  Palestine: ['State of Palestine', 'Palestinian Territories', 'Gaza'],
  Panama: ['PA'],
  'Papua New Guinea': ['PNG'],
  Paraguay: ['PY'],
  Philippines: ['The Philippines', 'Pilipinas', 'PH'],
  Poland: ['Polska', 'PL'],
  Portugal: ['PT'],
  'Puerto Rico': ['PR'],
  Romania: ['RO'],
  'Russian Federation': ['Russia', 'RU', 'RUS'],
  'Saint Kitts and Nevis': ['St Kitts and Nevis', 'St Kitts', 'Nevis'],
  'Saint Lucia': ['St Lucia'],
  'Saint Vincent and the Grenadines': ['St Vincent', 'Grenadines'],
  'Sao Tome and Principe': ['São Tomé and Príncipe', 'Sao Tome'],
  'Saudi Arabia': ['KSA', 'Kingdom of Saudi Arabia'],
  Singapore: ['SG', 'SGP'],
  Slovakia: ['Slovak Republic', 'SK'],
  Slovenia: ['SI'],
  'South Africa': ['RSA'],
  Spain: ['España', 'Espana', 'ES'],
  'Sri Lanka': ['Ceylon', 'LK'],
  Sweden: ['Sverige', 'SE'],
  Switzerland: ['Swiss', 'Schweiz', 'Suisse', 'CH'],
  Syria: ['Syrian Arab Republic'],
  Taiwan: ['Republic of China', 'ROC', 'Chinese Taipei', 'Formosa'],
  Tanzania: ['United Republic of Tanzania'],
  Thailand: ['Siam', 'TH'],
  'Timor-Leste': ['East Timor'],
  'Trinidad and Tobago': ['Trinidad', 'Tobago'],
  Tunisia: ['TN'],
  Turkey: ['Türkiye', 'Turkiye'],
  Ukraine: ['UA', 'Ukraina'],
  'United Arab Emirates': ['UAE', 'Emirates', 'Dubai', 'Abu Dhabi'],
  'United Kingdom': [
    'UK',
    'U.K.',
    'Great Britain',
    'Britain',
    'GB',
    'England',
    'Scotland',
    'Wales',
    'Northern Ireland',
  ],
  'United States': [
    'USA',
    'US',
    'U.S.',
    'U.S.A.',
    'America',
    'United States of America',
  ],
  Uruguay: ['UY'],
  Uzbekistan: ['UZ'],
  'Vatican City': ['Holy See', 'Vatican'],
  Venezuela: ['Bolivarian Republic of Venezuela'],
  'Viet Nam': ['Vietnam', 'VN'],
  Zambia: ['ZM'],
  Zimbabwe: ['Rhodesia'],

  // Regions
  'East Asia': ['Far East'],
  'East Asia & Pacific': ['EAP', 'Asia Pacific', 'APAC'],
  'Eastern Europe': ['East Europe'],
  Europe: ['EU', 'European Union'],
  'North Africa': ['Maghreb', 'Northern Africa'],
  'South America': ['Latin America', 'LATAM'],
  'South Asia': ['Indian Subcontinent', 'Subcontinent'],
  'Southeast Asia': ['SE Asia', 'South East Asia', 'ASEAN'],
  'West Asia': ['Middle East', 'Western Asia', 'Near East'],
  Australasia: ['Oceania'],

  // Territories
  Curaçao: ['Curacao'],
  Réunion: ['Reunion'],
  'Saint Barthélemy': ['Saint Barthelemy', 'St Barts'],
  'Åland Islands': ['Aland Islands', 'Aland'],
  Macau: ['Macao'],
  Greenland: ['Kalaallit Nunaat'],
  'U.S. Virgin Islands': ['US Virgin Islands', 'United States Virgin Islands'],
  'British Virgin Islands': ['BVI'],
  'Turks and Caicos Islands': ['Turks and Caicos'],
  'Faroe Islands': ['Faroes', 'Føroyar'],
  'Falkland Islands': ['Malvinas'],
  'French Polynesia': ['Tahiti'],
}

// Canonical names are seeded first so aliases win the tie: 'Czech Republic' is a
// flag key in its own right and must still resolve to 'Czechia'.
const CANONICAL_BY_NAME = new Map<string, string>()
for (const name of [
  ...Object.keys(COUNTRY_FLAGS),
  ...Object.keys(REGION_FLAGS),
]) {
  CANONICAL_BY_NAME.set(name.toLowerCase(), name)
}
for (const [canonical, aliases] of Object.entries(LOCATION_ALIASES)) {
  for (const alias of aliases) {
    CANONICAL_BY_NAME.set(alias.toLowerCase(), canonical)
  }
}

/** Unknown locations come back trimmed but untouched: X's vocabulary is X's. */
export function canonicalLocation(value: string): string {
  const trimmed = value.trim()
  return CANONICAL_BY_NAME.get(trimmed.toLowerCase()) ?? trimmed
}

// Deliberately generous and overlapping: over-inclusion costs a country the user
// adds back by name, under-inclusion costs a filter that does nothing.
export const REGION_MEMBERS: Record<string, string[]> = {
  'North America': [
    'Canada',
    'United States',
    'Mexico',
    'Guatemala',
    'Belize',
    'El Salvador',
    'Honduras',
    'Nicaragua',
    'Costa Rica',
    'Panama',
    'Cuba',
    'Jamaica',
    'Haiti',
    'Dominican Republic',
    'Bahamas',
    'Barbados',
    'Trinidad and Tobago',
    'Antigua and Barbuda',
    'Dominica',
    'Grenada',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Puerto Rico',
    'Bermuda',
    'Greenland',
    'Cayman Islands',
    'Aruba',
    'Curaçao',
    'Martinique',
    'Guadeloupe',
    'Anguilla',
    'Montserrat',
    'Turks and Caicos Islands',
    'British Virgin Islands',
    'U.S. Virgin Islands',
    'Saint Martin',
    'Sint Maarten',
    'Saint Barthélemy',
    'Saint Pierre and Miquelon',
  ],
  'South America': [
    'Argentina',
    'Bolivia',
    'Brazil',
    'Chile',
    'Colombia',
    'Ecuador',
    'Guyana',
    'Paraguay',
    'Peru',
    'Suriname',
    'Uruguay',
    'Venezuela',
    'French Guiana',
    'Falkland Islands',
  ],
  Europe: [
    'Albania',
    'Andorra',
    'Austria',
    'Belarus',
    'Belgium',
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Estonia',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Iceland',
    'Ireland',
    'Italy',
    'Kosovo',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Malta',
    'Moldova',
    'Monaco',
    'Montenegro',
    'Netherlands',
    'North Macedonia',
    'Norway',
    'Poland',
    'Portugal',
    'Romania',
    'Russian Federation',
    'San Marino',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Sweden',
    'Switzerland',
    'Turkey',
    'Ukraine',
    'United Kingdom',
    'Vatican City',
    'Isle of Man',
    'Jersey',
    'Guernsey',
    'Gibraltar',
    'Faroe Islands',
    'Åland Islands',
  ],
  'Eastern Europe': [
    'Albania',
    'Belarus',
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Czechia',
    'Estonia',
    'Hungary',
    'Kosovo',
    'Latvia',
    'Lithuania',
    'Moldova',
    'Montenegro',
    'North Macedonia',
    'Poland',
    'Romania',
    'Russian Federation',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Ukraine',
  ],
  'Eastern Europe (Non-EU)': [
    'Albania',
    'Belarus',
    'Bosnia and Herzegovina',
    'Kosovo',
    'Moldova',
    'Montenegro',
    'North Macedonia',
    'Russian Federation',
    'Serbia',
    'Ukraine',
  ],
  Africa: [
    'Algeria',
    'Angola',
    'Benin',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cameroon',
    'Central African Republic',
    'Chad',
    'Comoros',
    'Congo',
    'Democratic Republic of the Congo',
    'Djibouti',
    'Egypt',
    'Equatorial Guinea',
    'Eritrea',
    'Eswatini',
    'Ethiopia',
    'Gabon',
    'Gambia',
    'Ghana',
    'Guinea',
    'Guinea-Bissau',
    'Ivory Coast',
    'Kenya',
    'Lesotho',
    'Liberia',
    'Libya',
    'Madagascar',
    'Malawi',
    'Mali',
    'Mauritania',
    'Mauritius',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Niger',
    'Nigeria',
    'Rwanda',
    'Sao Tome and Principe',
    'Senegal',
    'Seychelles',
    'Sierra Leone',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Sudan',
    'Tanzania',
    'Togo',
    'Tunisia',
    'Uganda',
    'Zambia',
    'Zimbabwe',
    'Réunion',
    'Mayotte',
    'Western Sahara',
  ],
  'North Africa': [
    'Algeria',
    'Egypt',
    'Libya',
    'Morocco',
    'Sudan',
    'Tunisia',
    'Western Sahara',
  ],
  'West Asia': [
    'Armenia',
    'Azerbaijan',
    'Bahrain',
    'Cyprus',
    'Georgia',
    'Iraq',
    'Israel',
    'Jordan',
    'Kuwait',
    'Lebanon',
    'Oman',
    'Palestine',
    'Qatar',
    'Saudi Arabia',
    'Syria',
    'Turkey',
    'United Arab Emirates',
    'Yemen',
  ],
  'Central Asia': [
    'Kazakhstan',
    'Kyrgyzstan',
    'Tajikistan',
    'Turkmenistan',
    'Uzbekistan',
  ],
  'South Asia': [
    'Afghanistan',
    'Bangladesh',
    'Bhutan',
    'India',
    'Maldives',
    'Nepal',
    'Pakistan',
    'Sri Lanka',
  ],
  'East Asia': [
    'China',
    'Hong Kong',
    'Japan',
    'Korea',
    'Macau',
    'Mongolia',
    'North Korea',
    'Taiwan',
  ],
  'Southeast Asia': [
    'Brunei',
    'Cambodia',
    'Indonesia',
    'Laos',
    'Malaysia',
    'Myanmar',
    'Philippines',
    'Singapore',
    'Thailand',
    'Timor-Leste',
    'Viet Nam',
  ],
  Australasia: [
    'Australia',
    'New Zealand',
    'Fiji',
    'Papua New Guinea',
    'Solomon Islands',
    'Vanuatu',
    'Samoa',
    'Tonga',
    'Kiribati',
    'Tuvalu',
    'Nauru',
    'Marshall Islands',
    'Micronesia',
    'Palau',
    'French Polynesia',
    'New Caledonia',
    'Guam',
    'American Samoa',
    'Northern Mariana Islands',
    'Cook Islands',
    'Wallis and Futuna',
    'Christmas Island',
  ],
}

// Purely a union of the three, so it is derived rather than typed out again — a
// hand-copied fourth list would drift the first time a country moved.
REGION_MEMBERS['East Asia & Pacific'] = [
  ...new Set([
    ...REGION_MEMBERS['East Asia'],
    ...REGION_MEMBERS['Southeast Asia'],
    ...REGION_MEMBERS['Australasia'],
  ]),
]

/**
 * Members the user has unchecked under a blocked region, keyed by region: a
 * country dropped from one region is still blocked through another that keeps
 * it, and through its own chip.
 */
export type RegionExclusions = Record<string, string[]>

/** The members of `region` still covered by it. */
export function includedMembers(
  region: string,
  exclusions: RegionExclusions = {},
): string[] {
  const members = REGION_MEMBERS[region]
  if (!members) return []
  const dropped = new Set((exclusions[region] ?? []).map(canonicalLocation))
  return members.filter((m) => !dropped.has(canonicalLocation(m)))
}

/**
 * Each region replaced by itself plus the members it still covers — X reports
 * both shapes. Only the content script expands; storage keeps the user's picks
 * as they made them.
 */
export function expandLocations(
  list: Iterable<string>,
  exclusions: RegionExclusions = {},
): Set<string> {
  const out = new Set<string>()
  for (const raw of list) {
    const name = canonicalLocation(raw)
    out.add(name)
    for (const member of includedMembers(name, exclusions)) {
      out.add(canonicalLocation(member))
    }
  }
  return out
}

/** The regions a country belongs to, for explaining *why* something matched. */
export function regionsContaining(location: string): string[] {
  const name = canonicalLocation(location)
  return Object.keys(REGION_MEMBERS).filter((region) =>
    REGION_MEMBERS[region].some((m) => canonicalLocation(m) === name),
  )
}

/** The locations the options page offers, aliases folded away. */
export const CANONICAL_LOCATIONS = [
  ...Object.keys(COUNTRY_FLAGS),
  ...Object.keys(REGION_FLAGS),
]
  .filter((name) => canonicalLocation(name) === name)
  .sort((a, b) => a.localeCompare(b))

export const DEFAULT_BLOCKED_COUNTRIES = [
  'Africa',
  'India',
  'South Asia',
  'Nigeria',
  'Pakistan',
  'Bangladesh',
]
