/**
 * Writes the published test counts from what Vitest actually collects.
 *
 * The site states a number of tests as a claim about this repo, and a hand-typed
 * one drifts: it said 609 while the suite had grown past a thousand. Counting
 * `it(` with a regex is not good enough either — `it.each` is one call and many
 * tests, and the two disagreed by 208.
 *
 * `vitest list` collects without running, so this stays seconds rather than a
 * full suite. It is a script rather than part of the landing build because the
 * landing package would otherwise have to install and collect the extension's
 * whole test environment to render one table cell.
 *
 *   node scripts/count-tests.mjs
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** `vitest list` prints plugin warnings before the JSON; the array starts at a bare `[`. */
function collect(cwd) {
  const out = execFileSync('npx', ['vitest', 'list', '--json'], {
    cwd,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    stdio: ['ignore', 'pipe', 'ignore'],
  })
  const start = out.indexOf('\n[\n')
  const json = start === -1 ? out : out.slice(start + 1)
  return JSON.parse(json).length
}

const extension = collect(root)
const server = collect(join(root, 'server'))

writeFileSync(
  join(root, 'landing/src/data/test-count.ts'),
  `/**
 * Generated by \`pnpm tests:count\` — do not edit by hand.
 *
 * What \`vitest list\` collects, so the number the site publishes is the number
 * \`pnpm test\` runs.
 */
export const TEST_COUNT = ${extension}
export const SERVER_TEST_COUNT = ${server}
`,
)

const readmePath = join(root, 'README.md')
const readme = readFileSync(readmePath, 'utf8')
  .replace(/tests-\d+_passing/g, `tests-${extension}_passing`)
  .replace(/\d+ unit tests passing/g, `${extension} unit tests passing`)
  .replace(/runs \d+ unit tests/g, `runs ${extension} unit tests`)
  .replace(/plus \d+ for the cache server/g, `plus ${server} for the cache server`)
writeFileSync(readmePath, readme)

console.log(`extension ${extension} tests, cache server ${server} tests`)
